version: "3.8"
services:
  frontend:
    # build: ./frontend
    image: amploplatform.azurecr.io/frontend_onpremise:v0
    ports:
      - 3000:80
    networks:
      - amplo-net
  backend:
    # build: ./backend
    image: amploplatform.azurecr.io/backend_onpremise:v0
    tty: true
    environment:
      - ONPREMISE_KEY=${ONPREMISE_KEY}
      - ONPREMISE_TEAM=${ONPREMISE_TEAM}
      - INITIAL_ACCOUNT_MAIL=${INITIAL_ACCOUNT_MAIL}
      - DEVELOPMENT=${DEVELOPMENT}
      - TEST=${TEST}
    ports:
      - 8000:8080
      - 8001:8001
    volumes:
      - .:/usr/src/app # For Postgres persistency
      - type: volume
        source: AmploVolume
        target: /static
      # - type: bind
      #   source: /home/runner/work/MLDevPlatform
      #   target: /static
    depends_on:
      - db
      - redis
    networks:
      - amplo-net
  redis:
    image: redis:alpine
    networks:
      - amplo-net
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amplo
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - amplo-net
volumes:
  pgdata:
  AmploVolume:
networks:
  amplo-net:
    driver: bridge
