version: "3.8"
services:
  frontend:
    # build:
    #   context: ./frontend
    #   args:
    #     ON_PREMISE: "true"
    image: onpremiseamplo.azurecr.io/mldevplatform_frontend:v1.0.3
    ports:
      - 3000:80
    networks:
      - amplo-net
  backend:
    # build: ./backend
    image: onpremiseamplo.azurecr.io/mldevplatform_backend:v1.0.3
    environment:
      - AMPLO_MAIL_PASS=tDQE;6:k;dEL%xYpP)B\J4N;@_>(^tcYA"]ZNAMQ
      - AZURE_STORAGE_CONTAINER=amploplatform
      - AZURE_STORAGE_STRING=DefaultEndpointsProtocol=https;AccountName=amploplatformstorage;AccountKey=WF+KkTYhgZGGyTDUkUckSdDaSAJVbirrvryTr8m640wbzuqahXKBdQ5sKKcuAV+c07RJuNEiB2cUFH1yDNqZjw==;EndpointSuffix=core.windows.net
      - LOCAL_DB=${DB_OUTSIDE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - ON_PREMISE=True
      - ONPREMISE_KEY=${ONPREMISE_KEY}
      - ONPREMISE_TEAM=${ONPREMISE_TEAM}
      - INITIAL_ACCOUNT_MAIL=${INITIAL_ACCOUNT_MAIL}
    ports:
      - 8000:8080
      - 8001:8001
    volumes:
      - .:/usr/src/app # For Postgres persistency
      - type: volume
        source: AmploVolume
        target: /static
      # - type: bind
      #   source: C:/Users
      #   target: /static
    depends_on:
      - db
      - redis
    networks:
      - amplo-net
  redis:
    image: redis:alpine
    networks:
      - amplo-net
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amplo
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - amplo-net
volumes:
  pgdata:
  AmploVolume:
networks:
  amplo-net:
    driver: bridge
